### ISSUE TITLE
Issue Setting Transport Strategy w/ Spring Config

### ISSUE THREAD

**Issue by adamzr** [bbottema/simple-java-mail#129]
I am getting this error message:
`Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to org.simplejavamail.mailer.config.TransportStrategy
	at org.simplejavamail.mailer.Mailer.<init>(Mailer.java:221) ~[simple-java-mail-4.4.5.jar:na]
	at org.simplejavamail.mailer.Mailer.<init>(Mailer.java:143) ~[simple-java-mail-4.4.5.jar:na]
	at org.simplejavamail.springsupport.SimpleJavaMailSpringSupport.loadGlobalConfigAndCreateDefaultMailer(SimpleJavaMailSpringSupport.java:75) ~[simple-java-mail-4.4.5.jar:na]
	at org.simplejavamail.springsupport.SimpleJavaMailSpringSupport$$EnhancerBySpringCGLIB$$ede9507b.CGLIB$loadGlobalConfigAndCreateDefaultMailer$0(<generated>) ~[simple-java-mail-4.4.5.jar:na]
	at org.simplejavamail.springsupport.SimpleJavaMailSpringSupport$$EnhancerBySpringCGLIB$$ede9507b$$FastClassBySpringCGLIB$$8417b800.invoke(<generated>) ~[simple-java-mail-4.4.5.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.simplejavamail.springsupport.SimpleJavaMailSpringSupport$$EnhancerBySpringCGLIB$$ede9507b.loadGlobalConfigAndCreateDefaultMailer(<generated>) ~[simple-java-mail-4.4.5.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	... 63 common frames omitted
`

I am using:

`@Import(SimpleJavaMailSpringSupport.class)
`
and 

`simplejavamail.transportstrategy=SMTPS
`

**Comment by adamzr** [comment]
I noticed after this that I was using version 4. I switched to using the builder and upgraded, so I'm not sure if this is an issue on v5.
