### ISSUE TITLE
Timeout not honored

### ISSUE THREAD

**Issue by ben-manes** [bbottema/simple-java-mail#182]
I'm seeing an interesting case this morning which is blocking emails due to the mailer being hung and other threads waiting on the lock. The email in question has been stuck for a few hours, starting at 8:15 AM PST. The immediate solution is to bounce the machine, which will cause a retry. I think the external mail provider (Mailgun) must have had an hiccup.

Is there a mechanism to timeout this? I expected your session timeout to have kicked in, but perhaps there is another socket timeout flag to set somewhere? If its a `java.mail` setting, it would be good to document that and recommend better defaults.

```
"Quartz: notification:email.c135b1ea-8e36-4d8d-99ae-119eb2c3e624" #30 daemon prio=5 os_prio=0 tid=0x00007f6cee995800 nid=0x10c1 runnable  [0x00007f6c822f0000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(java.base@10.0.1/Native Method)
	at java.net.SocketInputStream.socketRead(java.base@10.0.1/SocketInputStream.java:116)
	at java.net.SocketInputStream.read(java.base@10.0.1/SocketInputStream.java:171)
	at java.net.SocketInputStream.read(java.base@10.0.1/SocketInputStream.java:141)
	at com.sun.mail.util.TraceInputStream.read(TraceInputStream.java:126)
	at java.io.BufferedInputStream.fill(java.base@10.0.1/BufferedInputStream.java:252)
	at java.io.BufferedInputStream.read(java.base@10.0.1/BufferedInputStream.java:271)
	- locked <0x000000064fd61a80> (a java.io.BufferedInputStream)
	at com.sun.mail.util.LineInputStream.readLine(LineInputStream.java:106)
	at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2440)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2187)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:740)
	- locked <0x000000064fd61b68> (a com.sun.mail.smtp.SMTPTransport)
	at javax.mail.Service.connect(Service.java:388)
	- locked <0x000000064fd61b68> (a com.sun.mail.smtp.SMTPTransport)
	at javax.mail.Service.connect(Service.java:246)
	at javax.mail.Service.connect(Service.java:195)
	at org.simplejavamail.mailer.internal.mailsender.MailSender.sendMailClosure(MailSender.java:265)
	at org.simplejavamail.mailer.internal.mailsender.MailSender.send(MailSender.java:211)
	- locked <0x0000000641d5d6c0> (a org.simplejavamail.mailer.internal.mailsender.MailSender)
	at org.simplejavamail.mailer.Mailer.sendMail(Mailer.java:239)
	- locked <0x0000000641d5d6a0> (a org.simplejavamail.mailer.Mailer)
	at org.simplejavamail.mailer.Mailer.sendMail(Mailer.java:230)

**Comment by bbottema** [comment]
I also would have expected the session timeout to kick in. Is it being overwritten by a properties file by any chance?

Fyi, the session time is managed by setting the following three JavaMail properties to the same value (in case of transport strategy SMTPS "smtp" is replaced with "smtps"):
1. mail.smtp.connectiontimeout
2. mail.smtp.timeout
3. mail.smtp.writetimeout

**Comment by ben-manes** [comment]
Nope, I didn't override that. My configuration is minimal, with a little complexity due to a rebrand to toggle the sender.

```
mail {
  host = smtp.mailgun.org
  port = 587
  mode = smtp_tls # smtp, smtps, smtp_tls
  api-key = <redacted>

  loaddocs {
    username = "postmaster@mg.loaddocs.co"
    password = <redacted>

    default-sender {
      name = "LoadDocs"
      email = "delivery@mg.loaddocs.co"
    }
  }
  vector {
    username = "postmaster@mg.withvector.com"
    password = <redacted>

    default-sender {
      name = "Vector"
      email = "delivery@mg.withvector.com"
    }
  }
}
```

```java
private void configureEmailers() {
  int port = config.getInt("mail.port");
  String host = config.getString("mail.host");
  TransportStrategy mode = TransportStrategy.valueOf(
      config.getString("mail.mode").toUpperCase(US));

  for (Settings.Sender sender : Settings.Sender.values()) {
    String username = config.getString("mail." + sender + ".username");
    String password = config.getString("mail." + sender + ".password");
    EmailContact defaultFrom = new EmailContact()
        .withName(config.getString("mail." + sender + ".default-sender.name"))
        .withEmail(config.getString("mail." + sender + ".default-sender.email"));
    Mailer mailer = MailerBuilder
        .withSMTPServer(host, port, username, password)
        .withTransportStrategy(mode)
        .buildMailer();
    MapBinder.newMapBinder(binder(), Settings.Sender.class, Emailer.class)
        .addBinding(sender).toInstance(Emailer.create(defaultFrom, mailer));
  }
}
```

**Comment by bbottema** [comment]
Are you able to reproduce this reliably? I'm having no issues on my side. Also, are you sending mails normally or with `async = true`

**Comment by ben-manes** [comment]
It was a one time occurrence and hasn’t repeated. I use the synchronous api. It seemed like a fluke but also should have timed out given the settings, so I reported it.

**Comment by bbottema** [comment]
I would have done the same :)

Please let me know if it repeats and I'll see what I can do to reproduce it.

**Comment by ben-manes** [comment]
I ran into this again today on v5.2.0. Any suggestions? Restarting the servers doesn't help...

```
"Quartz: notification:email.ee27e24d-7c4c-4596-980a-c1de41adb23a" #42 daemon prio=5 os_prio=0 cpu=2184113.65ms elapsed=334247.86s tid=0x00007f86a803b000 nid=0x34c2 runnable  [0x00007f86839da000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(java.base@11.0.4/Native Method)
	at java.net.SocketInputStream.socketRead(java.base@11.0.4/SocketInputStream.java:115)
	at java.net.SocketInputStream.read(java.base@11.0.4/SocketInputStream.java:168)
	at java.net.SocketInputStream.read(java.base@11.0.4/SocketInputStream.java:140)
	at sun.security.ssl.SSLSocketInputRecord.read(java.base@11.0.4/SSLSocketInputRecord.java:448)
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(java.base@11.0.4/SSLSocketInputRecord.java:68)
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(java.base@11.0.4/SSLSocketImpl.java:1104)
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(java.base@11.0.4/SSLSocketImpl.java:823)
	- locked <0x00000007b43258c8> (a sun.security.ssl.SSLSocketImpl$AppInputStream)
	at com.sun.mail.util.TraceInputStream.read(TraceInputStream.java:126)
	at java.io.BufferedInputStream.fill(java.base@11.0.4/BufferedInputStream.java:252)
	at java.io.BufferedInputStream.read(java.base@11.0.4/BufferedInputStream.java:271)
	- locked <0x00000007b3edc070> (a java.io.BufferedInputStream)
	at com.sun.mail.util.LineInputStream.readLine(LineInputStream.java:106)
	at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2440)
	at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2337)
	at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1823)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1300)
	- locked <0x00000007b431a198> (a com.sun.mail.smtp.SMTPTransport)
	at org.simplejavamail.mailer.internal.mailsender.MailSender.sendMailClosure(MailSender.java:266)
	at org.simplejavamail.mailer.internal.mailsender.MailSender.send(MailSender.java:211)
	- locked <0x0000000682182e28> (a org.simplejavamail.mailer.internal.mailsender.MailSender)
	at org.simplejavamail.mailer.Mailer.sendMail(Mailer.java:240)
	- locked <0x0000000682182e08> (a org.simplejavamail.mailer.Mailer)
	at org.simplejavamail.mailer.Mailer.sendMail(Mailer.java:231)
```

**Comment by ben-manes** [comment]
Is 60s for a read timeout excessive? This may be timing out but taking a long time, and blocking due to being under an internal lock, that it seems unresponsive.

```java
/**
  * The default maximum timeout value for the transport socket is {@value #DEFAULT_SESSION_TIMEOUT_MILLIS} milliseconds (affects socket connect-,
  * read- and write timeouts). Can be overridden from a config file or through System variable.
  */
@SuppressWarnings("JavaDoc")
public static final int DEFAULT_SESSION_TIMEOUT_MILLIS = 60_000;
```

**Comment by bbottema** [comment]
It seems this issue was forgotten. Where are we on this?

**Comment by ben-manes** [comment]
Its a non-issue because Mailgun forced me to switch to their proprietary apis due to their smtp gateway is intentionally unstable. They rotate IPs in/out to poison the DNS cache in order to protect against DoS attacks. The way they do this causes socket timeouts (if lucky) and they strongly implied that their API should be use for SaaS-level scale. The smtp is fine for product integrations that email rarely. So unfortunately no longer use this library and don't think this was your problem.
