### ISSUE TITLE
Class ConfigLoader Not Initialized

### ISSUE THREAD

**Issue by napperley** [bbottema/simple-java-mail#185]
When sending a email using Simple Java Mail the email isn't sent, and a exception appears:

```
Exception in thread "ForkJoinPool.commonPool-worker-2" java.lang.NoClassDefFoundError: Could not initialize class org.simplejavamail.util.ConfigLoader
	at org.simplejavamail.email.EmailPopulatingBuilder.<init>(EmailPopulatingBuilder.java:179)
	at org.simplejavamail.email.EmailBuilder$EmailBuilderInstance.startingBlank(EmailBuilder.java:199)
	at org.simplejavamail.email.EmailBuilder.startingBlank(EmailBuilder.java:138)
```

This is the function where the exception occurs (on the **EmailBuilder** line):

```kotlin
fun sendPlainEmail(
    fromAddr: String = "",
    fromName: String = "",
    toAddrList: Array<String>,
    toName: String = "",
    subject: String,
    msg: String
) {
    if (EmailSettings.enabled) {
        val email = EmailBuilder.startingBlank().apply {
            if (fromAddr.isNotEmpty()) from(fromName, fromAddr)
            if (toName.isEmpty()) to(toAddrList.joinToString()) else to(toName, toAddrList.joinToString())
            withSubject(subject)
            appendText(msg)
        }.buildEmail()

        logger.debug("Sending email...")
        try {
            mailer.sendMail(email)
        } catch (ex: MailException) {
            logger.warn("Can't send email: ${ex.message}")
        }
    }
}
```

Here is the **mailer** definition: 
```kotlin
private val mailer by lazy { MailerBuilder.buildMailer() }
```

Very odd that the **"missing"** class file is present in the Fat JAR (in the right place) yet the file cannot be found. Is Simple Java Mail compatible with JVM 9 and above?

Using OpenJDK 10.0.2,  Xubuntu 18.04, Gradle 5.0 (via Gradle Kotlin DSL), Simple Java Mail 5.1.0, and Kotlin 1.2.71.

**Comment by bbottema** [comment]
It should work fine with JVM 9 and above. I have know idea what's going wrong here.

**Comment by napperley** [comment]
Here is the full stack trace:
```
Exception in thread "ForkJoinPool.commonPool-worker-1" java.lang.NoClassDefFoundError: Could not initialize class org.simplejavamail.util.ConfigLoader
	at org.simplejavamail.email.EmailPopulatingBuilder.<init>(EmailPopulatingBuilder.java:179)
	at org.simplejavamail.email.EmailBuilder$EmailBuilderInstance.startingBlank(EmailBuilder.java:199)
	at org.simplejavamail.email.EmailBuilder.startingBlank(EmailBuilder.java:138)
	at com.chapman.solar_reader.ControllerKt.sendPlainEmail(controller.kt:55)
	at com.chapman.solar_reader.ControllerKt.sendPlainEmail$default(controller.kt:50)
	at com.chapman.solar_reader.Payload_monitorKt.notifyUsersByEmail(payload_monitor.kt:62)
	at com.chapman.solar_reader.Payload_monitorKt.issueAlarmAlert(payload_monitor.kt:137)
	at com.chapman.solar_reader.Payload_monitorKt.runCellDefinition(payload_monitor.kt:127)
	at com.chapman.solar_reader.Payload_monitorKt.applyCellDefinitions(payload_monitor.kt:51)
	at com.chapman.solar_reader.Payload_monitorKt.checkCells(payload_monitor.kt:38)
	at com.chapman.solar_reader.Payload_monitorKt.monitorChannelPayload(payload_monitor.kt:28)
	at com.chapman.solar_reader.SerialKt.processSerialPort(serial.kt:74)
	at com.chapman.solar_reader.SerialKt.access$processSerialPort(serial.kt:1)
	at com.chapman.solar_reader.SerialKt$runService$1$1$1.doResume(serial.kt:111)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:123)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by bbottema** [comment]
Well, that's not very helpful :/ I had hoped there would be a 'caused by' inclusion.

I see you're using fork/join, can you try making sure the code runs in a single thread? Perhaps there's a concurrency issue (although I don't see how class-loading in the JVM can be related to that).

**Comment by napperley** [comment]
Cause of the issue came from the **simplejavamail.properties** file. Turns out the custom property is rejected so the fix was to move the property to a different configuration file. Surprising that no error appeared about that in the stack trace.

**Comment by bbottema** [comment]
Well glad you got it sorted out. If you have any suggestion on how to improve on the error feedback, let me know!

**Comment by napperley** [comment]
Kotlin [Coroutines](https://kotlinlang.org/docs/reference/coroutines-overview.html) were **"tagged"** as experimental in Kotlin 1.1 and 1.2. Coroutines are [stable](https://kotlinlang.org/docs/reference/whatsnew13.html#coroutines-release) (no experimental tag) from Kotlin 1.3 on wards.
