### ISSUE TITLE
send mail with socks proxy error: java.net.SocketException: SOCKS : No acceptable methods

### ISSUE THREAD

**Issue by jrrx** [bbottema/simple-java-mail#197]
**Environment:** linux centos7 , java version "1.8.0_121
**Proxy Server:** centos7, installed ss5: http://ss5.sourceforge.net/
**Code like this:** 
Mailer mailer = MailerBuilder
                .withSMTPServer("smtp.xx.xx.com", 25, "myAccount", "myPassword")
                .withProxy("proxyIp", 1080, null, null)
                .withSessionTimeout(10 * 1000)
                .clearEmailAddressCriteria() // turns off email validation
                .withDebugLogging(true)
                .buildMailer();

mailer.sendMail(email);

**Error is:**
org.simplejavamail.mailer.internal.mailsender.MailSenderException: Third party error
	at org.simplejavamail.mailer.internal.mailsender.MailSender.sendMailClosure(MailSender.java:283)
	at org.simplejavamail.mailer.internal.mailsender.MailSender.send(MailSender.java:211)
	at org.simplejavamail.mailer.Mailer.sendMail(Mailer.java:239)
	at org.simplejavamail.mailer.Mailer.sendMail(Mailer.java:230)
...
...
Caused by: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.exmail.qq.com, 25; timeout -1; Using SOCKS host, port: x.x.x.x, 1080
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2209)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:740)
	at javax.mail.Service.connect(Service.java:388)
	at javax.mail.Service.connect(Service.java:246)
	at javax.mail.Service.connect(Service.java:195)
	at org.simplejavamail.mailer.internal.mailsender.MailSender.sendMailClosure(MailSender.java:265)
	... 58 common frames omitted
Caused by: java.net.SocketException: SOCKS : No acceptable methods
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:471)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:353)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:239)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2175)
	... 63 common frames omitted

**Comment by bbottema** [comment]
I have no idea. This exception is thrown by Java's own built-in Socket code as a result of your SOCKS server's response.

**Comment by Hans-Wu-cn** [comment]
Has it been resolved
