### ISSUE TITLE
API bugfix: server identity verification should not be tied to host trusting

### ISSUE THREAD

**Issue by floragunncom** [bbottema/simple-java-mail#221]
Simple Java Mail Version: 5.2.0

If I connect to a SMTP server on localhost with a self signed certificate and setting `MailerBuilder.trustingAllHosts(true)` and/or `MailerBuilder.trustingSSLHosts(new String[]{"*"})` get an "Can't verify identity of server: 127.0.0.1" exception:

```
org.simplejavamail.mailer.internal.mailsender.MailSenderException: Third party error
	at org.simplejavamail.mailer.internal.mailsender.MailSender.sendMailClosure(MailSender.java:283)
	at org.simplejavamail.mailer.internal.mailsender.MailSender.send(MailSender.java:211)
	at org.simplejavamail.mailer.Mailer.sendMail(Mailer.java:240)
	at org.simplejavamail.mailer.Mailer.sendMail(Mailer.java:231)
	at com.floragunn.signals.watch.actions.smtp.SmtpMailer.sendMail(SmtpMailer.java:53)
	at com.floragunn.signals.watch.actions.smtp.SmtpAction.execute(SmtpAction.java:81)
	at com.floragunn.signals.ActionTest.testSmtpAction(ActionTest.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: javax.mail.MessagingException: Could not connect to SMTP host: 127.0.0.1, port: 3000;
  nested exception is:
	java.io.IOException: Can't verify identity of server: 127.0.0.1
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2187)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:716)
	at javax.mail.Service.connect(Service.java:342)
	at javax.mail.Service.connect(Service.java:222)
	at javax.mail.Service.connect(Service.java:171)
	at org.simplejavamail.mailer.internal.mailsender.MailSender.sendMailClosure(MailSender.java:265)
	... 32 more
Caused by: java.io.IOException: Can't verify identity of server: 127.0.0.1
	at com.sun.mail.util.SocketFetcher.checkServerIdentity(SocketFetcher.java:673)
	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:610)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:376)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:214)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2151)
	... 37 more
```

I can fix it with `MailerBuilder..withProperty("mail.smtps.ssl.checkserveridentity", "false")` but for me it looks that `MailerBuilder.trustingAllHosts(true)` and/or `MailerBuilder.trustingSSLHosts(new String[]{"*"})` should imply this?

**Comment by bbottema** [comment]
What you are saying sounds reasonable, but unfortunately I'm not an expert on every topic Simple Java Mail touches, and this particular issue seems to stem from the SSL support in the underlying JavaMail library. Maybe we can page @cbarcenas and see if he has some ideas, he's been a great help in the past on similar topics.

**Comment by floragunncom** [comment]
@bbottema @cbarcenas

**Comment by floragunncom** [comment]
(Sorry, pressed wrong button)

@bbottema @cbarcenas the docs for 

- `trustingSSLHosts()` say "Configures the new session to only accept server certificates issued to one of the provided hostnames, and disables certificate issue validation"

- `trustingAllHosts()` say: "Configures the current session to trust all hosts and don't validate any SSL keys."

So in both cases "no validation" should happen which IMHO should imply mail.smtps.ssl.checkserveridentity=false

**Comment by bbottema** [comment]
`trustingSSLHosts` indicates not trusting all host and "mail.smtps.ssl.checkserveridentity" is not selective so that's not a good match.

Actually I [read](https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summary.html) that `checkserveridentity` defaults to false if not set and I've seen some [examples](https://stackoverflow.com/questions/16683606/spring-javamailsenderimpl-is-not-working-with-ssl) that set it to true in combination with SSL trusting.

Could it be that checkserveridentity should be set to true in order for trusting hosts to work as intended? I'm going to dive into the JavaMail sources, but perhaps you can test this hypothesis already, @floragunncom?

**Comment by bbottema** [comment]
After conducting a source code review of JavaMail, it seems these properties serve different purposes and its exposure in Simple Java Mail misaligned.

Trusting a host means that after verifying its identity, you say you don't distrust it. If you leave it empty, you trust it by default. It's like an optional whitelist, but is not related to verifying the server's identity using SSL keys.

Knowing this, I'm still thinking about what is the best way to expose this API better. Would it make sense to expose both features separately, or roll it all into one method (like the current `trustingHosts()`).

**Comment by bbottema** [comment]
I think I will split it up in two methods: one to enable/disable server identity checks using SSL key and one that enables the whitelist for hosts (not related to SSL).

**Comment by bbottema** [comment]
@floragunncom, I've released a SNAPSHOT version with the API split up, 5.4.0-SNAPSHOT.

You can now do:
```
mailerBuilder
   .verifyingServerIdentity(false)
   .buildMailer();
```
Probably you don't need to touch `trustingHosts` or `trustingAllHosts`, but in case you are not using SSL/TLS, setting your server as trusted host would be prudent (using both is even better).

(you'll need to [add the snapshot repo](https://stackoverflow.com/a/7717234/441662)).

Can you verify this solved your issue, @floragunncom?

**Comment by floragunncom** [comment]
+1, thx

**Comment by bbottema** [comment]
Will release 5.4.0 soon to Maven Central, but OSS Sonatype is currently experiencing networking issues preventing new deploys.

**Comment by bbottema** [comment]
5.4.0 released.

**Comment by bbottema** [comment]
Historical follow-up: #677 builds on the separation established here. In Simple Java Mail 9.2.0, certificate-authority trust uses the JVM trust store by default while hostname verification remains enabled. Named-host and trust-all exceptions remain explicit compatibility options.
