### ISSUE TITLE
fail to send mail with non english file name by AWS SES

### ISSUE THREAD

**Issue by mivatekkrisc** [bbottema/simple-java-mail#224]
AWS SES didn't accept message as following.

> Content-Type: image/jpg; filename==?UTF-8?Q?=E4=B8=AD=E6=96=87.jpg?=; name==?UTF-8?Q?=E4=B8=AD=E6=96=87
> Content-Transfer-Encoding: base64
> Content-Disposition: attachment; 
> 	filename="=?UTF-8?Q?=E4=B8=AD=E6=96=87.jpg?="
> Content-ID: <=?UTF-8?Q?=E4=B8=AD=E6=96=87>

It always response org.simplejavamail.mailer.internal.mailsender.MailSenderException: Third party error

 java.mail API will generate following message for non english file name and that's ok for AWS SES.

> Content-Type: image/jpg; name="=?UTF-8?B?5Lit5paHLmpwZw==?="
> Content-Transfer-Encoding: base64
> Content-Disposition: attachment; filename="=?UTF-8?B?5Lit5paHLmpwZw==?="

**Comment by bbottema** [comment]
That's not much information to go on. What was the stacktrace? What is the actual non-English name?

Perhaps the problem is actually the file name (which Simple Java Mail adds) rather than the name.

Also, as a workaround, its possible to provide your own name for data sources that you embed. If you escape that name to a safe string it should work.

**Comment by mivatekkrisc** [comment]
2019-08-30 00:46:33,219 pool-3-thread-379 ERROR 1195687100 1000963252 USER 257 OPSmtpEmailServiceImpl - Third party error
org.simplejavamail.mailer.internal.mailsender.MailSenderException: Third party error
	at org.simplejavamail.mailer.internal.mailsender.MailSender.sendMailClosure(MailSender.java:283) ~[simple-java-mail-5.2.0.jar:na]
	at org.simplejavamail.mailer.internal.mailsender.MailSender.send(MailSender.java:211) ~[simple-java-mail-5.2.0.jar:na]
	at org.simplejavamail.mailer.Mailer.sendMail(Mailer.java:240) ~[simple-java-mail-5.2.0.jar:na]
	at org.simplejavamail.mailer.Mailer.sendMail(Mailer.java:231) ~[simple-java-mail-5.2.0.jar:na]
	at com.oplk.platform.opguard.core.service.impl.OPSmtpEmailServiceImpl.sendMail(OPSmtpEmailServiceImpl.java:211) ~[core-0.0.1-SNAPSHOT.jar:na]
	at com.oplk.platform.opguard.core.service.impl.OPSmtpEmailServiceImpl.sendMail(OPSmtpEmailServiceImpl.java:185) ~[core-0.0.1-SNAPSHOT.jar:na]
	at com.oplk.platform.opguard.server.service.impl.SmtpEmailServiceImpl.lambda$sendMail$1(SmtpEmailServiceImpl.java:114) ~[core-0.0.1-SNAPSHOT.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: com.sun.mail.smtp.SMTPSendFailedException: 554 Transaction failed: Expected ';', got "CAM.jpg"

	at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2334) ~[jakarta.mail-1.6.3.jar:1.6.3]
	at com.sun.mail.smtp.SMTPTransport.finishData(SMTPTransport.java:2086) ~[jakarta.mail-1.6.3.jar:1.6.3]
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1292) ~[jakarta.mail-1.6.3.jar:1.6.3]
	at org.simplejavamail.mailer.internal.mailsender.MailSender.sendMailClosure(MailSender.java:266) ~[simple-java-mail-5.2.0.jar:na]
	... 9 common frames omitted

**Comment by mivatekkrisc** [comment]
We send an mail with attachment "PT CAM.jpg" is also reject by SES.
It look like AWS mail server did not accept Content-Type: image/jpg; filename==?UTF-8?Q?=E4=B8=AD=E6=96=87.jpg?=; name==?UTF-8?Q?=E4=B8=AD=E6=96=87

We try to modify MimeMessageHelper as following and that's working for AWS SES.
attachmentPart.setHeader("Content-Type",
                contentType + "; filename=\"" + fileName + "\"; name=\"" + resourceName + "\"");

**Comment by bbottema** [comment]
I would like to reproduce the problem myself. Can you share your code or an example that triggers this behavior?

**Comment by mivatekkrisc** [comment]
`Mailer mailer = MailerBuilder.withSMTPServer(host, port, user, pwd).withDebugLogging(true).buildMailer();
        
        EmailPopulatingBuilder emailBuilder = EmailBuilder.startingBlank()
                .from(from, from).to(to).withSubject("主旨").withHTMLText("<html>test</html>");
        
        emailBuilder.withAttachment("PT CAM.jpg", data, "image/jpg");
        Email email = emailBuilder.buildEmail();
        
        mailer.sendMail(email);`

**Comment by bbottema** [comment]
Have you tried other mail servers? Is it only AWS rejecting it?

**Comment by mivatekkrisc** [comment]
Yes, only AWS SES reject it. Godaddy mail server is fine with that.

**Comment by bbottema** [comment]
Ok, then I suggest you file a bug with them, because I can't see anything wrong with the emails.
