### ISSUE TITLE
Issue found on version 5.5.1 

### ISSUE THREAD

**Issue by aalfaro** [bbottema/simple-java-mail#234]
Hi, I'm creating a SpringBoot (2.2.1.RELEASE) application to read a gmail inbox , the msg is getting retrieved but I'm facing this issue when trying to convert the received MimeMessage to a simple-java-mail Email object using the EmailConverter.mimeMessageToEmail(mimeMessage) method. Below you can find the error , a snippet of related code and the simple-java-mail version used in the POM file.

s.integration.mail.ImapMailReceiver    : attempting to receive mail from folder [INBOX]
Message: GenericMessage [payload=org.springframework.integration.mail.AbstractMailReceiver$IntegrationMimeMessage@2703a5c4, headers={id=2701840f-0f42-0a6d-e6db-dc8c2d7fd9d9, timestamp=1573625274270}]
org.simplejavamail.converter.internal.mimemessage.MimeMessageParseException: Error getting all headers
	at org.simplejavamail.converter.internal.mimemessage.MimeMessageParser.retrieveAllHeaders(MimeMessageParser.java:244)
	at org.simplejavamail.converter.internal.mimemessage.MimeMessageParser.parseMimePartTree(MimeMessageParser.java:114)
	at org.simplejavamail.converter.internal.mimemessage.MimeMessageParser.parseMimePartTree(MimeMessageParser.java:127)
	at org.simplejavamail.converter.internal.mimemessage.MimeMessageParser.parseMimeMessage(MimeMessageParser.java:108)
	at org.simplejavamail.converter.EmailConverter.mimeMessageToEmailBuilder(EmailConverter.java:64)
	at org.simplejavamail.converter.EmailConverter.mimeMessageToEmail(EmailConverter.java:55)
	at com.myapp.Application$1.handleMessage(Application.java:42)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:461)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:403)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:198)
	at org.springframework.integration.mail.ImapIdleChannelAdapter.lambda$prepareSendingTask$0(ImapIdleChannelAdapter.java:223)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.mail.FolderClosedException
	at com.sun.mail.imap.IMAPMessage.getProtocol(IMAPMessage.java:169)
	at com.sun.mail.imap.IMAPBodyPart.loadHeaders(IMAPBodyPart.java:430)
	at com.sun.mail.imap.IMAPBodyPart.getAllHeaders(IMAPBodyPart.java:372)
	at org.simplejavamail.converter.internal.mimemessage.MimeMessageParser.retrieveAllHeaders(MimeMessageParser.java:242)
	... 21 more

-----------------------------------------------------------------------------------------------

`
public void handleMessage(org.springframework.messaging.Message<?> message) throws MessagingException {

javax.mail.internet.MimeMessage mimeMessage;
Email email;
String sender;
String subject;
String body;
Object payload = message.getPayload();

if (payload instanceof javax.mail.internet.MimeMessage) {
						
	mimeMessage = (MimeMessage) payload;
	email = EmailConverter.mimeMessageToEmail(mimeMessage);
	sender = email.getFromRecipient().getAddress();
	subject = email.getSubject();
	body = email.getPlainText();
						
	System.out.println("Sender: " + sender);
	System.out.println("Subject: " + subject);
	System.out.println("Body: " + body);
				
}
`

`
<dependency>
   <groupId>org.simplejavamail</groupId>
   <artifactId>simple-java-mail</artifactId>
   <version>5.5.1</version>
</dependency>
`

**Comment by aalfaro** [comment]
Having the same issue using the apache **commons-email** library -> https://commons.apache.org/proper/commons-email 

So my issue might not be related to your library, instead it seems to be more related to a org.springframework.integration issue since the main exception is javax.mail.FolderClosedException

I did some research and I found some other cases where the same issue is happening when using similar code and approach (Spring Integration) For now I found a work around and this is not longer an issue for me, therefore I'm closing this issue. Thanks !

**Comment by bbottema** [comment]
Ahh ok, glad to hear you worked it out! Yeah it seems like the mimemessage is lazy loading data from a remote IMAP folder (is that even possible)? I'm not too familiar with the IMAP protocol though.
