### ISSUE TITLE
IllegalArgumentException: Implicit NotNull argument 6

### ISSUE THREAD

**Issue by TuguldurJ** [bbottema/simple-java-mail#240]
@bbottema, Thank you for contributing and simplifying java-mail!

I followed instructions on [Spring Support](http://www.simplejavamail.org/configuration.html#section-spring-support).

But some default argument is missing or configuration class not found. 
My Configuration Class
`
@Component
@Import(SimpleJavaMailSpringSupport.class)
public class MailConfiguration {
	@Resource
	private Mailer mailer;
}
`

Please look at log.

`Caused by: java.lang.IllegalArgumentException: Implicit NotNull argument 6 of org/simplejavamail/springsupport/SimpleJavaMailSpringSupport.loadGlobalConfigAndCreateDefaultMailer must not be null`

Full log:

```
--- 'mailConfiguration': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultMailer' defined in class path resource [org/simplejavamail/springsupport/SimpleJavaMailSpringSupport.class]: Unsatisfied dependency expressed through method 'defaultMailer' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultMailerBuilder' defined in class path resource [org/simplejavamail/springsupport/SimpleJavaMailSpringSupport.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.simplejavamail.api.mailer.MailerGenericBuilder]: Factory method 'loadGlobalConfigAndCreateDefaultMailer' threw exception; nested exception is java.lang.IllegalArgumentException: Implicit NotNull argument 6 of org/simplejavamail/springsupport/SimpleJavaMailSpringSupport.loadGlobalConfigAndCreateDefaultMailer must not be null
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:337)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultMailer' defined in class path resource [org/simplejavamail/springsupport/SimpleJavaMailSpringSupport.class]: Unsatisfied dependency expressed through method 'defaultMailer' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultMailerBuilder' defined in class path resource [org/simplejavamail/springsupport/SimpleJavaMailSpringSupport.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.simplejavamail.api.mailer.MailerGenericBuilder]: Factory method 'loadGlobalConfigAndCreateDefaultMailer' threw exception; nested exception is java.lang.IllegalArgumentException: Implicit NotNull argument 6 of org/simplejavamail/springsupport/SimpleJavaMailSpringSupport.loadGlobalConfigAndCreateDefaultMailer must not be null
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:537)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:513)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:653)
	at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:224)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:116)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:334)
	... 22 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultMailerBuilder' defined in class path resource [org/simplejavamail/springsupport/SimpleJavaMailSpringSupport.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.simplejavamail.api.mailer.MailerGenericBuilder]: Factory method 'loadGlobalConfigAndCreateDefaultMailer' threw exception; nested exception is java.lang.IllegalArgumentException: Implicit NotNull argument 6 of org/simplejavamail/springsupport/SimpleJavaMailSpringSupport.loadGlobalConfigAndCreateDefaultMailer must not be null
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:656)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789)
	... 40 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.simplejavamail.api.mailer.MailerGenericBuilder]: Factory method 'loadGlobalConfigAndCreateDefaultMailer' threw exception; nested exception is java.lang.IllegalArgumentException: Implicit NotNull argument 6 of org/simplejavamail/springsupport/SimpleJavaMailSpringSupport.loadGlobalConfigAndCreateDefaultMailer must not be null
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)
	... 54 more
Caused by: java.lang.IllegalArgumentException: Implicit NotNull argument 6 of org/simplejavamail/springsupport/SimpleJavaMailSpringSupport.loadGlobalConfigAndCreateDefaultMailer must not be null
	at org.simplejavamail.springsupport.SimpleJavaMailSpringSupport.loadGlobalConfigAndCreateDefaultMailer(SimpleJavaMailSpringSupport.java)
	at org.simplejavamail.springsupport.SimpleJavaMailSpringSupport$$EnhancerBySpringCGLIB$$8f884d25.CGLIB$loadGlobalConfigAndCreateDefaultMailer$0(<generated>)
	at org.simplejavamail.springsupport.SimpleJavaMailSpringSupport$$EnhancerBySpringCGLIB$$8f884d25$$FastClassBySpringCGLIB$$5e776de8.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at org.simplejavamail.springsupport.SimpleJavaMailSpringSupport$$EnhancerBySpringCGLIB$$8f884d25.loadGlobalConfigAndCreateDefaultMailer(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 55 more
```

**Comment by bbottema** [comment]
Aww, that's one of the few places left without automated regression test (until now).

Bug fixed and released in 6.0.0-rc2, but I can't release it now as OSS Sonatype is having network issues [yet again](https://issues.sonatype.org/projects/OSSRH/issues/OSSRH-53951?filter=allopenissues).

**Comment by bbottema** [comment]
It seems the release went through finally.

**Comment by bbottema** [comment]
6.0.0 has released as well, finally.
