### ISSUE TITLE
554 Transaction failed: Missing start boundary with AWS mail

### ISSUE THREAD

**Issue by castortech** [bbottema/simple-java-mail#259]
Having an issue sending a simple email with text and html (text only is Ok with 6.0.3)

With debug on I get (with emails and accounts changed):
```
250 Ok
RCPT TO:<xyz@example.com>
250 Ok
DEBUG SMTP: Verified Addresses
DEBUG SMTP:   "xyz@example.com" <xyz@example.com>
DATA
354 End data with <CR><LF>.<CR><LF>
Date: Wed, 22 Apr 2020 13:44:45 -0400 (EDT)
From: "abc@example.com" <abc@example.com>
To: "xyz@example.com" <xyz@example.com>
Message-ID: <103932435.2.1587577485940@[192.168.128.210]>
Subject: Test Email
MIME-Version: 1.0
Content-Type: multipart/alternative; 
	boundary="----=_Part_1_2129897145.1587577485940"

.
554 Transaction failed: Missing start boundary
DEBUG SMTP: got response code 554, with response: 554 Transaction failed: Missing start boundary

RSET
250 Ok
DEBUG SMTP: MessagingException while sending, THROW: 
com.sun.mail.smtp.SMTPSendFailedException: 554 Transaction failed: Missing start boundary

	at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2334)
	at com.sun.mail.smtp.SMTPTransport.finishData(SMTPTransport.java:2086)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1292)
	at org.simplejavamail.mailer.internal.util.TransportRunner$1.run(TransportRunner.java:52)
	at org.simplejavamail.mailer.internal.util.TransportRunner.runOnSessionTransport(TransportRunner.java:76)
	at org.simplejavamail.mailer.internal.util.TransportRunner.sendMessage(TransportRunner.java:48)
	at org.simplejavamail.mailer.internal.SendMailClosure.executeClosure(SendMailClosure.java:78)
	at org.simplejavamail.mailer.internal.AbstractProxyServerSyncingClosure.run(AbstractProxyServerSyncingClosure.java:56)
	at org.simplejavamail.mailer.internal.MailerImpl.sendMail(MailerImpl.java:330)
	at org.simplejavamail.mailer.internal.MailerImpl.sendMail(MailerImpl.java:316)
	at com.castortech.util.mail.EmailUtils.sendMail(EmailUtils.java:90)
	...
QUIT
221 Bye
13:44:47.315 [] ERROR o.s.m.i.AbstractProxyServerSyncingClosure - Failed to send email:
Email{
	id=<103932435.2.1587577485940@[192.168.128.210]>
	sentDate=null
	fromRecipient=Recipient{name='abc@example.com', address='abc@example.com', type=null},
	replyToRecipient=null,
	bounceToRecipient=null,
	text='This is a test email',
	textHTML='<p>This is a <b>test</b> email</p>',
	textCalendar='null (method: null)',
	subject='Test Email',
	recipients=[Recipient{name='xyz@example.com', address='xyz@example.com', type=To}]
}

```

**Comment by bbottema** [comment]
I have no clue, seems like an issue with the server itself. Have you looked around what might cause this?

**Comment by castortech** [comment]
Googled quite a bit and most of the time it's related to AWS mail.

But what I'm not sure I understand from the debug log, is that we see the boundary as "----= but never see the message parts, like this example here:

```
Content-Type: multipart/mixed;
 boundary="--==_mimepart_5114d2f18f621_7028125080411632";
 charset=UTF-8
Content-Transfer-Encoding: 7bit



----==_mimepart_5114d2f18f621_7028125080411632
Date: Fri, 08 Feb 2013 10:26:57 +0000
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment;
 filename=foo.txt
filename: foo.txt
Content-ID: <5114d2f0ee34b_7028125080411545@ip-10-62-103-46.mail>

Hallo

----==_mimepart_5114d2f18f621_7028125080411632
Date: Fri, 08 Feb 2013 10:26:57 +0000
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Content-ID: <5114d2f19ce45_7028125080411785@ip-10-62-103-46.mail>



----==_mimepart_5114d2f18f621_7028125080411632--

```
which is why I was suspecting something possibly below my interaction level.

Thanks
Alain

**Comment by bbottema** [comment]
Is it possible for you to share the email with me? You can use the EmailConverter to convert an Email object to EML string.

**Comment by castortech** [comment]
Here in between with another log statement after:

```
14:28:04.346 [] INFO  c.c.u.m.EmailUtils - EML:Date: Thu, 23 Apr 2020 14:28:04 -0400 (EDT)
From: "xxx@xxx.com" <xxx@xxx.com>
To: "xyz@xyz.com" <xyz@xyz.com>
Message-ID: <411650110.5.1587666484346@[192.168.128.210]>
Subject: Test Email
MIME-Version: 1.0
Content-Type: multipart/alternative; 
 	boundary="----=_Part_4_792693233.1587666484261"
 
 

14:28:04.360 [] INFO  c.c.u.m.EmailUtils - end

```
and the expected message is:
```
Email{
	id=<1691050744.3.1587666435285@[192.168.128.210]>
	sentDate=null
	fromRecipient=Recipient{name='xxx@xxx.com', address='xxx@xxx.com', type=null},
	replyToRecipient=null,
	bounceToRecipient=null,
	text='This is a test email',
	textHTML='<p>This is a <b>test</b> email</p>',
	textCalendar='null (method: null)',
	subject='Test Email',
	recipients=[Recipient{name='xyz@xyz.com', address='xyz@xyz.com', type=To}]
}

```

**Comment by bbottema** [comment]
That's the full EML output of the conversion??

**Comment by castortech** [comment]
Yes, that felt strange to me as well.

**Comment by castortech** [comment]
Well your last comment made me realize that this was very similar to issue #147 that I had reported and now that I upgraded I lost my changes. So had to rebuild a custom version. Sorry for this.
