### ISSUE TITLE
Issues Sending a signed email

### ISSUE THREAD

**Issue by tnycruz** [bbottema/simple-java-mail#353]
Hi,

I'm testing the sign email feature and i'm having issues with the email sign.

My code right now is very simple and looks like this:

		Pkcs12Config myKeyInfo = Pkcs12Config.builder()
			    .pkcs12Store(<path>)
			    .storePassword(<password>)
			    .keyAlias(<alias>)
			    .keyPassword(<password>)
			    .build();

		
		
		Email email = EmailBuilder.startingBlank()
				.from(<someemail>)

		          .to(<someemail>)
		          .withSubject(<somesubject>)
		          .withPlainText(<sometext>)
		          .signWithSmime(myKeyInfo)
		          .buildEmail();

		Mailer mailer = MailerBuilder
		          .withSMTPServer(<someip>, 25)
		          .withProperty("mail.smtp.sendpartial", true)
		          .withDebugLogging(true)
		          .buildMailer();

		mailer.sendMail(email);

When it sends the email it always gives an error:

java.io.IOException: "text/plain" DataContentHandler requires String object, was given object of type class javax.mail.internet.MimeMultipart
	at com.sun.mail.handlers.text_plain.writeTo(text_plain.java:97)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:889)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1089)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1527)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:321)
	at org.simplejavamail.mailer.internal.util.TransportRunner$1.run(TransportRunner.java:52)
	at org.simplejavamail.mailer.internal.util.TransportRunner.runOnSessionTransport(TransportRunner.java:76)
	at org.simplejavamail.mailer.internal.util.TransportRunner.sendMessage(TransportRunner.java:48)
	at org.simplejavamail.mailer.internal.SendMailClosure.executeClosure(SendMailClosure.java:82)
	at org.simplejavamail.mailer.internal.AbstractProxyServerSyncingClosure.run(AbstractProxyServerSyncingClosure.java:56)
	at org.simplejavamail.mailer.internal.MailerImpl.sendMail(MailerImpl.java:345)
	at org.simplejavamail.mailer.internal.MailerImpl.sendMail(MailerImpl.java:331)
        ...

Does someone already have this issue? It could something with my code or perhaps some dependencies (i think i've double check on this, but...)

Thanks,

Antonio Cruz

**Comment by bbottema** [comment]
Which version are you on? If you would share your files with me (here on in email) I could try to reproduce the problem...

**Comment by bbottema** [comment]
Closing until further input is provided.
