### ISSUE TITLE
Problems with Content-Type : multipart/signed

### ISSUE THREAD

**Issue by JulBerthelot** [bbottema/simple-java-mail#366]
HI,
I'm using the simple-java-mail library to send emails based on eml files. Overall it works great, but everytime I try to read an eml file which contains 'Content-Type : multipart/signed' with the EmailConverter.emlToEmail method, I get an exception.
It seems the library doesn't handle this MIME type. Do you have any information about it ?

**Comment by bbottema** [comment]
_multipart/signed_ means content signed using S/MIME and Simple Java Mail will attempt to verify the signature, I think. It's hard to tell what is going wrong without error or stacktrace, or a test eml file that I can use to reproduce this issue. Which version are you on? How are you calling the API?

**Comment by JulBerthelot** [comment]
I'm using the 6.5.2 version and I'm calling the API like this :
            
             
            String emlSrcURL = creationDiffusionCmd.getEmailOriginal().getMessagePath();
            Path emlSrcPath = Path.of(emlSrcURL);
            Optional<Email> emailSrc = Optional.empty();
            try {
                emailSrc = Optional.of(EmailConverter.emlToEmail(emlSrcPath.toFile()));
            } catch (MailException e) {
                log.error("Could not read email from file {}", emlSrcPath, e);
            }

If I use the library with this eml file :
```
MIME-Version: 1.0
To: ben@example.com
From: ann@example.com
Subject: Multi-part signed message
Date: Mon, 23 Feb 2004 12:00:52 +1100
Content-Type: multipart/signed;
    micalg=SHA1;
    boundary="----=_NextBoundry";
    protocol="application/pkcs7-signature"

This is a multi-part message in MIME format.

------=_NextBoundry

This is some sample content.
------=_NextBoundry
Content-Type: application/pkcs7-signature; name=smime.p7s
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=smime.p7s

MIIDeQYJKoZIhvcNAQcCoIIDajCCA2YCAQExCTAHBgUrDgMCGjALBgkqhkiG9w0BBwGggg
LiMIIC3jCCAp2gAwIBAgICAMgwCQYHKoZIzjgEAzASMRAwDgYDVQQDEwdDYXJsRFNTMB4X
...

------=_NextBoundry--
```
I have the following exception :
```
net.markenwerk.utils.mail.smime.SmimeException: IOException reading content.

	at net.markenwerk.utils.mail.smime.SmimeUtil.handledException(SmimeUtil.java:615)
	at net.markenwerk.utils.mail.smime.SmimeUtil.checkSignature(SmimeUtil.java:464)
	at org.simplejavamail.internal.smimesupport.SMIMESupport.verifyValidSignature(SMIMESupport.java:382)
	at org.simplejavamail.internal.smimesupport.SMIMESupport.checkSignature(SMIMESupport.java:176)
	at org.simplejavamail.internal.smimesupport.SMIMESupport.finalizeSmimeMetadata(SMIMESupport.java:168)
	at org.simplejavamail.internal.smimesupport.SMIMESupport.decryptAttachments(SMIMESupport.java:136)
	at org.simplejavamail.internal.smimesupport.SMIMESupport.decryptAttachments(SMIMESupport.java:91)
	at org.simplejavamail.converter.EmailConverter.decryptAttachments(EmailConverter.java:245)
	at org.simplejavamail.converter.EmailConverter.mimeMessageToEmailBuilder(EmailConverter.java:120)
	at org.simplejavamail.converter.EmailConverter.emlToEmailBuilder(EmailConverter.java:338)
	at org.simplejavamail.converter.EmailConverter.emlToEmail(EmailConverter.java:322)
	at org.simplejavamail.converter.EmailConverter.emlToEmail(EmailConverter.java:314)
	at fr.maif.ged.flux.integration.accuse.reception.mail.editique.domaine.service.EditorService.editer(EditorService.java:159)
	at fr.maif.ged.flux.integration.accuse.reception.mail.test.selection.domaine.EditorServiceITest.replyMailSigned(EditorServiceITest.java:94)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.bouncycastle.cms.CMSException: IOException reading content.
	at org.bouncycastle.cms.CMSUtils.readContentInfo(Unknown Source)
	at org.bouncycastle.cms.CMSUtils.readContentInfo(Unknown Source)
	at org.bouncycastle.cms.CMSSignedData.<init>(Unknown Source)
	at org.bouncycastle.mail.smime.SMIMESigned.<init>(Unknown Source)
	at net.markenwerk.utils.mail.smime.SmimeUtil.checkSignature(SmimeUtil.java:457)
	... 44 more
Caused by: java.io.EOFException: DEF length 889 object truncated by 788
	at org.bouncycastle.asn1.DefiniteLengthInputStream.read(Unknown Source)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:83)
	at org.bouncycastle.asn1.DefiniteLengthInputStream.read(Unknown Source)
	at org.bouncycastle.asn1.DefiniteLengthInputStream.read(Unknown Source)
	at org.bouncycastle.asn1.DefiniteLengthInputStream.read(Unknown Source)
	at org.bouncycastle.asn1.DefiniteLengthInputStream.read(Unknown Source)
	at org.bouncycastle.asn1.DefiniteLengthInputStream.read(Unknown Source)
	at org.bouncycastle.asn1.DefiniteLengthInputStream.read(Unknown Source)
	at org.bouncycastle.asn1.ASN1InputStream.readLength(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.DERSequenceParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.DERSequenceParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.DERSequenceParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readTaggedObject(Unknown Source)
	at org.bouncycastle.asn1.BERTaggedObjectParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.DERSequenceParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readTaggedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1InputStream.buildObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1InputStream.readObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1InputStream.buildEncodableVector(Unknown Source)
	at org.bouncycastle.asn1.ASN1InputStream.buildDEREncodableVector(Unknown Source)
	at org.bouncycastle.asn1.ASN1InputStream.buildObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1InputStream.readObject(Unknown Source)
	... 49 more
```

**Comment by bbottema** [comment]
Would you mind trying this with the latest Java7 release of Simple Java Mail, 6.7.5? Also, I'm releasing 7.0.0 soon, which updates to a newer bouncycastle which might fix it.

**Comment by JulBerthelot** [comment]
I gonna wait for the 7.0.0.

**Comment by bbottema** [comment]
7.0.0 just got released so you can give that a try.

**Comment by bbottema** [comment]
And?

**Comment by bbottema** [comment]
Closing until further input is provided that warrants reopening.
