### ISSUE TITLE
"java.lang.ClassNotFoundException: jakarta.mail.Session" In Spring Boot

### ISSUE THREAD

**Issue by Jycjmf** [bbottema/simple-java-mail#384]
Hi guys , I was trying to use this library in Spring Boot 2.6.3 with java 17 , I have follow the steps in [https://www.simplejavamail.org/configuration.html#section-spring-support](url)

Here is my Maven dependency:
```
        <dependency>
            <groupId>org.simplejavamail</groupId>
            <artifactId>simple-java-mail</artifactId>
            <version>7.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.simplejavamail</groupId>
            <artifactId>spring-module</artifactId>
            <version>7.1.0</version>
        </dependency>
```
And `application.properties`:
```
logging.level.root=debug
simplejavamail.javaxmail.debug=true
simplejavamail.smtp.host=smtp.qq.com
simplejavamail.smtp.port=587
simplejavamail.transportstrategy=SMTP_TLS
simplejavamail.defaults.sessiontimeoutmillis=60000
simplejavamail.smtp.username=username
simplejavamail.smtp.password=password

```
In `DemoApplication.java` , For testing , I just use dependency injection with `@Autowired`  without any other functional codes, but it cannot work:
```
@SpringBootApplication
@Import(SimpleJavaMailSpringSupport.class)
public class DemoApplication implements CommandLineRunner {
    @Autowired
    private Mailer mailer;
    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }
    @Override
    public void run(String... args) throws Exception {

    }
}
```
Here is the stack trace:
```
2022-02-18 23:12:30.552 ERROR 3768 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'demoApplication': Unsatisfied dependency expressed through field 'mailer'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultMailer' defined in org.simplejavamail.springsupport.SimpleJavaMailSpringSupport: Unsatisfied dependency expressed through method 'defaultMailer' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultMailerBuilder' defined in org.simplejavamail.springsupport.SimpleJavaMailSpringSupport: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.simplejavamail.api.mailer.MailerGenericBuilder]: Factory method 'loadGlobalConfigAndCreateDefaultMailer' threw exception; nested exception is java.lang.NoClassDefFoundError: jakarta/mail/Session
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.6.3.jar:2.6.3]
	at com.example.demo.DemoApplication.main(DemoApplication.java:21) ~[classes/:na]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultMailer' defined in org.simplejavamail.springsupport.SimpleJavaMailSpringSupport: Unsatisfied dependency expressed through method 'defaultMailer' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultMailerBuilder' defined in org.simplejavamail.springsupport.SimpleJavaMailSpringSupport: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.simplejavamail.api.mailer.MailerGenericBuilder]: Factory method 'loadGlobalConfigAndCreateDefaultMailer' threw exception; nested exception is java.lang.NoClassDefFoundError: jakarta/mail/Session
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656) ~[spring-beans-5.3.15.jar:5.3.15]
	... 20 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultMailerBuilder' defined in org.simplejavamail.springsupport.SimpleJavaMailSpringSupport: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.simplejavamail.api.mailer.MailerGenericBuilder]: Factory method 'loadGlobalConfigAndCreateDefaultMailer' threw exception; nested exception is java.lang.NoClassDefFoundError: jakarta/mail/Session
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.15.jar:5.3.15]
	... 33 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.simplejavamail.api.mailer.MailerGenericBuilder]: Factory method 'loadGlobalConfigAndCreateDefaultMailer' threw exception; nested exception is java.lang.NoClassDefFoundError: jakarta/mail/Session
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.15.jar:5.3.15]
	... 47 common frames omitted
Caused by: java.lang.NoClassDefFoundError: jakarta/mail/Session
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[na:na]
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3543) ~[na:na]
	at java.base/java.lang.Class.getMethod0(Class.java:3529) ~[na:na]
	at java.base/java.lang.Class.getMethod(Class.java:2225) ~[na:na]
	at java.base/java.lang.Class.getEnumConstantsShared(Class.java:3828) ~[na:na]
	at java.base/java.lang.Class.enumConstantDirectory(Class.java:3859) ~[na:na]
	at java.base/java.lang.Enum.valueOf(Enum.java:267) ~[na:na]
	at org.simplejavamail.api.mailer.config.TransportStrategy.valueOf(TransportStrategy.java:34) ~[core-module-7.1.0.jar:na]
	at org.simplejavamail.config.ConfigLoader.parsePropertyValue(ConfigLoader.java:460) ~[core-module-7.1.0.jar:na]
	at org.simplejavamail.config.ConfigLoader.readProperties(ConfigLoader.java:393) ~[core-module-7.1.0.jar:na]
	at org.simplejavamail.config.ConfigLoader.loadProperties(ConfigLoader.java:319) ~[core-module-7.1.0.jar:na]
	at org.simplejavamail.springsupport.SimpleJavaMailSpringSupport.loadGlobalConfigAndCreateDefaultMailer(SimpleJavaMailSpringSupport.java:218) ~[spring-module-7.1.0.jar:na]
	at org.simplejavamail.springsupport.SimpleJavaMailSpringSupport$$EnhancerBySpringCGLIB$$b12f5546.CGLIB$loadGlobalConfigAndCreateDefaultMailer$0(<generated>) ~[spring-module-7.1.0.jar:na]
	at org.simplejavamail.springsupport.SimpleJavaMailSpringSupport$$EnhancerBySpringCGLIB$$b12f5546$$FastClassBySpringCGLIB$$6e096fac.invoke(<generated>) ~[spring-module-7.1.0.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.15.jar:5.3.15]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.15.jar:5.3.15]
	at org.simplejavamail.springsupport.SimpleJavaMailSpringSupport$$EnhancerBySpringCGLIB$$b12f5546.loadGlobalConfigAndCreateDefaultMailer(<generated>) ~[spring-module-7.1.0.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.15.jar:5.3.15]
	... 48 common frames omitted
Caused by: java.lang.ClassNotFoundException: jakarta.mail.Session
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 71 common frames omitted

Disconnected from the target VM, address: '127.0.0.1:57994', transport: 'socket'

Process finished with exit code 1

```
Could anyone help me with this problem ? thanks !

**Comment by bbottema** [comment]
This means that Simple Java Mail's transitive dependency JakartaMail is not on the classpath somehow. Are you excluding it somewhere? Or if you use one, is it missing on your application server? In any case, not something I can solve for you.

**Comment by Jycjmf** [comment]
> JakartaMail
Hi @bbottema , Sorry for such meaningless problems ,I have already set the JakartaMail dependency in the project ,but it still not work, Does what I do in the picture means adding the dependency to classpath ? Many thanks.
![image](https://user-images.githubusercontent.com/30173232/155319390-f1f0c83f-6e3a-4086-a529-0c65b1adc24f.png)
![image](https://user-images.githubusercontent.com/30173232/155319582-839a6351-ac5f-4012-918c-a1a98c09aa45.png)

**Comment by bbottema** [comment]
All the needed dependencies are named in the Maven dependencies. It seems you have an outdated version of Jakarta.

You need these versions: https://github.com/bbottema/simple-java-mail/blob/ac08444d60ece0f4c9349a3b5e5a638b8538ed66/modules/core-module/pom.xml#L26-L36

**Comment by Jycjmf** [comment]
> <dependency> 
>      <groupId>com.sun.mail</groupId> 
>      <artifactId>jakarta.mail</artifactId> 
>      <version>2.0.1</version> 
>  </dependency> 
>  <dependency> 
>      <groupId>com.sun.activation</groupId> 
>      <artifactId>jakarta.activation</artifactId> 
>      <version>2.0.1</version> 
>  </dependency>

Thanks bro , What you said has solved my problems , Sorry for the mess.
