### ISSUE TITLE
cant send email on openjdk version "1.8.0_352"

### ISSUE THREAD

**Issue by salithfish** [bbottema/simple-java-mail#428]
**IN openjdk version "1.8.0_312", i can use to send mail.
but in openjdk version "1.8.0_352", i got somthing wrong. the code is the same.**
here is the exception:
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_352]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_352]
        at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[na:1.8.0_352]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_352]
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:464) ~[na:1.8.0_352]
        at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68) ~[na:1.8.0_352]
        at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1346) ~[na:1.8.0_352]
        at sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:73) ~[na:1.8.0_352]
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:962) ~[na:1.8.0_352]
        at com.sun.mail.util.TraceInputStream.read(TraceInputStream.java:102) ~[jakarta.mail-2.0.1.jar:2.0.1]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_352]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[na:1.8.0_352]
        at com.sun.mail.util.LineInputStream.readLine(LineInputStream.java:100) ~[jakarta.mail-2.0.1.jar:2.0.1]
        at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2456) ~[jakarta.mail-2.0.1.jar:2.0.1]
        ... 62 common frames omitted
org.simplejavamail.mailer.internal.MailerException: Failed to send email [<735697252.4.1671083325884@iZbp144worluc97xvj3czeZ>], reason: Third party error
        at org.simplejavamail.mailer.internal.SendMailClosure.handleException(SendMailClosure.java:97) ~[simple-java-mail-7.5.0.jar:na]
        at org.simplejavamail.mailer.internal.SendMailClosure.executeClosure(SendMailClosure.java:89) ~[simple-java-mail-7.5.0.jar:na]
        at org.simplejavamail.mailer.internal.AbstractProxyServerSyncingClosure.run(AbstractProxyServerSyncingClosure.java:56) ~[simple-java-mail-7.5.0.jar:na]
        at org.simplejavamail.mailer.internal.MailerImpl.sendMail(MailerImpl.java:345) ~[simple-java-mail-7.5.0.jar:na]
        at org.simplejavamail.mailer.internal.MailerImpl.sendMail(MailerImpl.java:331) ~[simple-java-mail-7.5.0.jar:na]
        at com.pile.app.controller.home.HomeAppController.testEmail(HomeAppController.java:308) ~[classes/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_352]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_352]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_352]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_352]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) ~[spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814) ~[spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737) ~[spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) ~[spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) ~[spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:871) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:652) [servlet-api.jar:na]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845) [spring-webmvc-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) [servlet-api.jar:na]

**Comment by bbottema** [comment]
I'm a little skeptical about this. Are you telling me that you consistently have success with 1.8.0_312 and consistently fails with the other? No other dependencies changed also?

At any rate socket timeouts is not something I can fix on my end. This is a connection issue with your mail server that's not working out somehow.

**Comment by bbottema** [comment]
Closing until I'm convinced this is not a user error and there is something more to go on.
