### ISSUE TITLE
java.lang.NoClassDefFoundError: jakarta/activation/FileTypeMap

### ISSUE THREAD

**Issue by laglangyue** [bbottema/simple-java-mail#432]
I don't know why the dependency is not imported.

**Comment by laglangyue** [comment]
<dependency>
        <groupId>org.simplejavamail</groupId>
        <artifactId>simple-java-mail</artifactId>
        <version>${simple-java-mail.version}</version>
      </dependency>

**Comment by laglangyue** [comment]
It's OK after I import the dependency.

    <dependency>
      <groupId>com.sun.mail</groupId>
      <artifactId>jakarta.mail</artifactId>

    </dependency>
    <dependency>
      <groupId>com.sun.activation</groupId>
      <artifactId>jakarta.activation</artifactId>
    </dependency>

**Comment by bbottema** [comment]
Glad you got it working!

**Comment by laglangyue** [comment]
这是否意味着我只引入
simple-java-mail 无法发送mail，需要引入依赖包
Does this mean that I only introduce

Simple java mail cannot send mail, and dependency packages need to be introduced

**Comment by laglangyue** [comment]
Does this mean that I only introduce

Simple-java-mail cannot send mail, and dependency packages need to be introduced

**Comment by laglangyue** [comment]
Are dependencies not automatically imported？

**Comment by laglangyue** [comment]
@bbottema Can you help me with this

> Are dependencies not automatically imported？

**Comment by bbottema** [comment]
Yes, they are regular compile-time maven dependencies and maven should import them automatically.

**Comment by laglangyue** [comment]
> Yes, they are regular compile-time maven dependencies and maven should import them automatically.
> 
> <img alt="image" width="828" src="https://user-images.githubusercontent.com/2115718/211273678-f81ca9eb-c6d6-46cc-879c-bb246c6b9dad.png">

Thx,

I can't send email,
```
Caused by: jakarta.mail.MessagingException: No MimeMessage content
	at jakarta.mail.internet.MimeMessage.getContentStream(MimeMessage.java:1395) ~[jakarta.mail-2.0.1.jar:2.0.1]
	at jakarta.mail.internet.MimeBodyPart$MimePartDataHandler.getContentStream(MimeBodyPart.java:1703) ~[jakarta.mail-2.0.1.jar:2.0.1]
	at jakarta.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1659) ~[jakarta.mail-2.0.1.jar:2.0.1]
	at jakarta.mail.internet.MimeMessage.writeTo(MimeMessage.java:1888) ~[jakarta.mail-2.0.1.jar:2.0.1]
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1300) ~[jakarta.mail-2.0.1.jar:2.0.1]
	at org.simplejavamail.mailer.internal.util.TransportRunner.lambda$sendMessage$0(TransportRunner.java:48) ~[simple-java-mail-7.6.0.jar:?]
	at org.simplejavamail.mailer.internal.util.TransportRunner.runOnSessionTransport(TransportRunner.java:68) ~[simple-java-mail-7.6.0.jar:?]
	at org.simplejavamail.mailer.internal.util.TransportRunner.sendMessage(TransportRunner.java:47) ~[simple-java-mail-7.6.0.jar:?]
	at org.simplejavamail.mailer.internal.SendMailClosure.executeClosure(SendMailClosure.java:84) ~[simple-java-mail-7.6.0.jar:?]
	... 75 more

```

**Comment by laglangyue** [comment]
Email email = EmailBuilder.startingBlank()
          .from(mailProperties.getFromName(), mailProperties.getFrom())
          .to(messageModel.getReceiver(), messageModel.getReceiver())
          .withSubject(messageModel.getTitle())
          .withHTMLText(messageModel.getComponent())
          .buildEmail();

**Comment by bbottema** [comment]
I'm not sure why you would get this. Please log the email using `yourEmail.toString()`

**Comment by laglangyue** [comment]
Thx a lot， I solve the problem,the content of my email is null.And I send my email successfully.
@bbottema
