### ISSUE TITLE
DKIM: bug on reading DNS TXT for DKIM long public key?

### ISSUE THREAD

**Issue by WinstonHKLee** [bbottema/simple-java-mail#44]
Hi I am newbie to GitHub.
SimpleJavaMail ported markenwerk/java-utils-mail-dkim, nice and thanks.
However I am not sure where I should post this issue, since markenwerk/java-utils-mail-dkim has no tab for "issue" and simple-java-mail is active here.
Anyway, while testing DKIM signing feature, I got the exception:

```
Obtaining the domain key for hubble.makedifferent.net.m failed
net.markenwerk.utils.mail.dkim.DkimSigningException: Obtaining the domain key for hubble.makedifferent.net.m failed
        at net.markenwerk.utils.mail.dkim.DkimSigner.sign(DkimSigner.java:442) ~[bin/:na]
        [...]
Caused by: java.io.IOException: net.markenwerk.utils.mail.dkim.DkimException: The public key MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDQw4AU7D/BKYINWOJJCjZ5OJJ7FzeuWU/B001/1yvxwtAvd/cuH3fRbWT0DUu49T+4igPwlCFnDkCkYvnY5otUPCGE8" CYOE6gx5FId0vX1X+CfEAcpqQZhTXr1kUUH6rbT6oiTAnGvkFhPP5PUICU6P9wZ0WJocsrkCVPYgXrQJQIDAQAB couldn't be read.
        at net.markenwerk.utils.mail.dkim.DkimSigningException.<init>(DkimSigningException.java:77) ~[bin/:na]
        ... 6 common frames omitted
Caused by: net.markenwerk.utils.mail.dkim.DkimException: The public key MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDQw4AU7D/BKYINWOJJCjZ5OJJ7FzeuWU/B001/1yvxwtAvd/cuH3fRbWT0DUu49T+4igPwlCFnDkCkYvnY5otUPCGE8" CYOE6gx5FId0vX1X+CfEAcpqQZhTXr1kUUH6rbT6oiTAnGvkFhPP5PUICU6P9wZ0WJocsrkCVPYgXrQJQIDAQAB couldn't be read.
        at net.markenwerk.utils.mail.dkim.DomainKey.getPublicKey(DomainKey.java:144) ~[bin/:na]
        [...]
Exception in thread "main" org.codemonkey.simplejavamail.MailException: Third party error: Obtaining the domain key for hubble.makedifferent.net.m failed
        at org.codemonkey.simplejavamail.Mailer.sendMail(Mailer.java:257)
        [...]
Caused by: net.markenwerk.utils.mail.dkim.DkimSigningException: Obtaining the domain key for hubble.makedifferent.net.m failed;
  nested exception is:
        java.io.IOException: net.markenwerk.utils.mail.dkim.DkimException: The public key MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDQw4AU7D/BKYINWOJJCjZ5OJJ7FzeuWU/B001/1yvxwtAvd/cuH3fRbWT0DUu49T+4igPwlCFnDkCkYvnY5otUPCGE8" CYOE6gx5FId0vX1X+CfEAcpqQZhTXr1kUUH6rbT6oiTAnGvkFhPP5PUICU6P9wZ0WJocsrkCVPYgXrQJQIDAQAB couldn't be read.
        at net.markenwerk.utils.mail.dkim.DkimSigner.sign(DkimSigner.java:442)
        [...]
Caused by: java.io.IOException: net.markenwerk.utils.mail.dkim.DkimException: The public key MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDQw4AU7D/BKYINWOJJCjZ5OJJ7FzeuWU/B001/1yvxwtAvd/cuH3fRbWT0DUu49T+4igPwlCFnDkCkYvnY5otUPCGE8" CYOE6gx5FId0vX1X+CfEAcpqQZhTXr1kUUH6rbT6oiTAnGvkFhPP5PUICU6P9wZ0WJocsrkCVPYgXrQJQIDAQAB couldn't be read.
        at net.markenwerk.utils.mail.dkim.DkimSigningException.<init>(DkimSigningException.java:77)
        ... 6 more
Caused by: net.markenwerk.utils.mail.dkim.DkimException: The public key MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDQw4AU7D/BKYINWOJJCjZ5OJJ7FzeuWU/B001/1yvxwtAvd/cuH3fRbWT0DUu49T+4igPwlCFnDkCkYvnY5otUPCGE8" CYOE6gx5FId0vX1X+CfEAcpqQZhTXr1kUUH6rbT6oiTAnGvkFhPP5PUICU6P9wZ0WJocsrkCVPYgXrQJQIDAQAB couldn't be read.
        at net.markenwerk.utils.mail.dkim.DomainKey.getPublicKey(DomainKey.java:144)
        [...]
```

Checking my DKIM public key:
```
> dig m._domainkey.hubble.makedifferent.net TXT
;; ANSWER SECTION:
m._domainkey.hubble.makedifferent.net. 13888 IN TXT "v=DKIM1\; k=rsa\; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDQw4AU7D/BKYINWOJJCjZ5OJJ7FzeuWU/B001/1yvxwtAvd/cuH3fRbWT0DUu49T+4igPwlCFnDkCkYvnY5otUPCGE8" "CYOE6gx5FId0vX1X+CfEAcpqQZhTXr1kUUH6rbT6oiTAnGvkFhPP5PUICU6P9wZ0WJocsrkCVPYgXrQJQIDAQAB"
```

However in DomainKeyUtil.getValue(String) it retrieved as:
```
"v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDQw4AU7D/BKYINWOJJCjZ5OJJ7FzeuWU/B001/1yvxwtAvd/cuH3fRbWT0DUu49T+4igPwlCFnDkCkYvnY5otUPCGE8" CYOE6gx5FId0vX1X+CfEAcpqQZhTXr1kUUH6rbT6oiTAnGvkFhPP5PUICU6P9wZ0WJocsrkCVPYgXrQJQIDAQAB
```

I supposed it was due to multiple lines of TXT (DKIM) record:
https://help.directadmin.com/item.php?id=552

Therefore I made an override after String value = (String) txtRecord.get();

```
			String value = (String) txtRecord.get();
			if (null == value) {
				throw new DkimException("Value of RR " + recordName + " couldn't be retrieved");
			}
			value = bugfixMultipleLinesTxt(value);
```
```

	private static String bugfixMultipleLinesTxt(String value) {
		if (value.endsWith("\""))
			return value;

		if (value.startsWith("\"")) {
			value = value.substring(1);
		}
		int p = value.indexOf("\" ");
		while (p != -1) {
			value = value.substring(0, p) + value.substring(p + 2);
			p = value.indexOf("\" ");
		}
		return value;
	}
```

Then it works. Signature verified pass by Gmail Yahoo Microsoft.
Hardly believe that `Attributes attributes = dnsContext.getAttributes(recordName, new String[] { "TXT" });` comes from `javax.naming.directory.DirContext.getAttributes(String, String[])`
Did I misunderstand anything?

**Comment by bbottema** [comment]
Thanks for your work @WinstonHKLee , I'll take a look at it this weekend.

**Comment by bbottema** [comment]
I sent an email to the maintainer, but haven't received a reply yet.

In the mean I've started forking the code, but it seems the owner made some changes to the code so I'm not sure whether your changes have become obsolete.

I will release a patch update when I'm done migrating to the new DKIM api.

**Comment by bbottema** [comment]
@WinstonHKLee Alright, got a reply back, you should be able to create an issue now there.

https://github.com/markenwerk/java-utils-mail-dkim/issues
