### ISSUE TITLE
InternalEmail.java throws IllegalStateException("Email was not marked as complete. This is a bug in Simple Java Mail. Please report this issue.")

### ISSUE THREAD

**Issue by oanagoanta-td** [bbottema/simple-java-mail#462]
Using V 8.1.0.
Previously used version: 5.5.1
When upgrading without changing any options, we get this exception
```
java.lang.IllegalStateException: Email was not marked as complete. This is a bug in Simple Java Mail. Please report this issue.
	at org.simplejavamail.email.internal.InternalEmail.verifyDefaultsAndOverridesApplied(InternalEmail.java:80)
	at org.simplejavamail.converter.internal.mimemessage.MimeMessageProducerHelper.produceMimeMessage(MimeMessageProducerHelper.java:55)
```

**Comment by bbottema** [comment]
Closing as inactionable.
