### ISSUE TITLE
S/MIME implementation is broken

### ISSUE THREAD

**Issue by KamoheloTang** [bbottema/simple-java-mail#469]
java.lang.NoClassDefFoundError: javax/mail/MessagingException
	at org.simplejavamail.utils.mail.smime.SmimeUtil.prepareGenerator(SmimeUtil.java:232)
	at org.simplejavamail.utils.mail.smime.SmimeUtil.encrypt(SmimeUtil.java:135)
	at org.simplejavamail.utils.mail.smime.SmimeUtil.encrypt(SmimeUtil.java:113)
	at org.simplejavamail.internal.smimesupport.SMIMESupport.encryptMessageWithSmime(SMIMESupport.java:464)
	at org.simplejavamail.converter.internal.mimemessage.SpecializedMimeMessageProducer.populateMimeMessage(SpecializedMimeMessageProducer.java:85)
	at org.simplejavamail.converter.internal.mimemessage.MimeMessageProducerHelper.produceMimeMessage(MimeMessageProducerHelper.java:58)
	at org.simplejavamail.mailer.internal.SessionBasedEmailToMimeMessageConverter.convertMimeMessage(SessionBasedEmailToMimeMessageConverter.java:127)
	at org.simplejavamail.mailer.internal.SessionBasedEmailToMimeMessageConverter.convertAndLogMimeMessage(SessionBasedEmailToMimeMessageConverter.java:102)
	at org.simplejavamail.mailer.internal.SessionBasedEmailToMimeMessageConverter.convertAndLogMimeMessage(SessionBasedEmailToMimeMessageConverter.java:79)
	at org.simplejavamail.mailer.internal.util.TransportRunner.lambda$sendMessage$0(TransportRunner.java:52)
	at org.simplejavamail.mailer.internal.util.TransportRunner.runOnSessionTransport(TransportRunner.java:73)
	at org.simplejavamail.mailer.internal.util.TransportRunner.sendMessage(TransportRunner.java:51)
	at org.simplejavamail.mailer.internal.SendMailClosure.executeClosure(SendMailClosure.java:69)
	at org.simplejavamail.mailer.internal.AbstractProxyServerSyncingClosure.run(AbstractProxyServerSyncingClosure.java:56)
	at org.simplejavamail.mailer.internal.MailerImpl.sendMail(MailerImpl.java:364)
	at org.simplejavamail.mailer.internal.MailerImpl.sendMail(MailerImpl.java:349)
	at com.example.services.SimpleEmailService.send(SimpleEmailService.java:32)

**Comment by bbottema** [comment]
Closing as inactionable. No version, usage code, environment details, or build tools mentioned.
