### ISSUE TITLE
Bug: 'IllegalArgumentException: emailAddressList is required' when  parsing mail with incorrect recipients from Outlook message

### ISSUE THREAD

**Issue by piu130** [bbottema/simple-java-mail#482]
When parsing an msg with an invalid recipient, the parser throws `IllegalArgumentException: emailAddressList is required`.

Would be nice to either do it like outlook client and just return (render) the name without email or ignore it completely without failing.

Her is an example: [emailAddressList_is_required.zip](https://github.com/bbottema/simple-java-mail/files/13615167/emailAddressList_is_required.zip)

Stacktrace (v8.3.3):
```
java.lang.IllegalArgumentException: emailAddressList is required
    at org.simplejavamail.internal.util.Preconditions.verifyNonnullOrEmpty(Preconditions.java:49)
    at org.simplejavamail.internal.util.Preconditions.checkNonEmptyArgument(Preconditions.java:30)
    at org.simplejavamail.internal.util.MiscUtil.extractEmailAddresses(MiscUtil.java:166)
    at org.simplejavamail.email.internal.EmailPopulatingBuilderImpl.withRecipients(EmailPopulatingBuilderImpl.java:1457)
    at org.simplejavamail.email.internal.EmailPopulatingBuilderImpl.to(EmailPopulatingBuilderImpl.java:870)
    at org.simplejavamail.internal.outlooksupport.converter.OutlookEmailConverter.copyReceiversFromOutlookMessage(OutlookEmailConverter.java:175)
    at org.simplejavamail.internal.outlooksupport.converter.OutlookEmailConverter.buildEmailFromOutlookMessage(OutlookEmailConverter.java:115)
    at org.simplejavamail.internal.outlooksupport.converter.OutlookEmailConverter.outlookMsgToEmailBuilder(OutlookEmailConverter.java:89)
    at org.simplejavamail.converter.EmailConverter.outlookMsgToEmailBuilder(EmailConverter.java:250)
    at org.simplejavamail.converter.EmailConverter.outlookMsgToEmail(EmailConverter.java:228)
    at org.simplejavamail.converter.EmailConverter.outlookMsgToEmail(EmailConverter.java:220)
    ...
```

**Comment by bbottema** [comment]
Fixed in 8.3.5. Thanks for reporting!
