### ISSUE TITLE
Proxy socket closed when connecting to authenticated proxy

### ISSUE THREAD

**Issue by avew** [bbottema/simple-java-mail#49]
I use proxy and after finish email was sending, however show exception like this. 

```java
Exception in thread "Thread-5" org.simplejavamail.mailer.internal.socks.common.SocksException: server crashed...
	at org.simplejavamail.mailer.internal.socks.socks5server.AnonymousSocks5Server.checkIoException(AnonymousSocks5Server.java:91)
	at org.simplejavamail.mailer.internal.socks.socks5server.AnonymousSocks5Server.run(AnonymousSocks5Server.java:76)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Socket closed
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at org.simplejavamail.mailer.internal.socks.socks5server.AnonymousSocks5Server.run(AnonymousSocks5Server.java:72)
	... 1 more
```

**Comment by bbottema** [comment]
The Socket was closed unexpectedly by the external proxy server for whatever reason. Is it a SOCKS proxy? I haven't tested it, but I think only SOCKS5 is supported by Simple Java Mail (I don't think SOCKS5 is backwards compatible with SOCKS4, but I'm not sure).

Or the remote proxy might see it fit to close the connection because it didn't recognize you based on your IP, or it rejected your username by closing the connection rather than sending an Unauthorized code.

Perhaps you can get the logs from the proxy? Or test the proxy some other way?

**Comment by avew** [comment]
For this case I do not get on the proxy server error log. but I'll try to check again using a proxy server to another. What I'm confused her emails sent but there is an error log. I would first try with another proxy server.
thank you
