### ISSUE TITLE
java.lang.NoClassDefFoundError: org/jacoco/agent/rt/internal_c13123e/Offline

### ISSUE THREAD

**Issue by meeximum** [bbottema/simple-java-mail#505]
I'm using latest version 8.8.1

and get the following error

Caused by: java.lang.NoClassDefFoundError: org/jacoco/agent/rt/internal_c13123e/Offline
        at org.bbottema.clusteredobjectpool.core.ClusterConfig.$jacocoInit(ClusterConfig.java)
        at org.bbottema.clusteredobjectpool.core.ClusterConfig.builder(ClusterConfig.java)
        at org.simplejavamail.smtpconnectionpool.SmtpClusterConfig.<init>(SmtpClusterConfig.java:50)
        at org.simplejavamail.internal.batchsupport.ClusterHelper.configureSmtpClusterConfig(ClusterHelper.java:40)
        at org.simplejavamail.internal.batchsupport.BatchSupport.ensureClusterInitialized(BatchSupport.java:97)
        at org.simplejavamail.internal.batchsupport.BatchSupport.registerToCluster(BatchSupport.java:87)
        at org.simplejavamail.mailer.internal.MailerImpl.initCluster(MailerImpl.java:297)
        at org.simplejavamail.mailer.internal.MailerImpl.<init>(MailerImpl.java:141)
        at org.simplejavamail.mailer.internal.MailerImpl.<init>(MailerImpl.java:119)
        at org.simplejavamail.mailer.internal.MailerRegularBuilderImpl.buildMailer(MailerRegularBuilderImpl.java:210)
        at at.balecon.portal.services.MailerService.<init>(MailerService.java:42)
        at at.balecon.portal.services.MailerService.getInstance(MailerService.java:32)
        at at.balecon.portal.ui.UserWPB.sendInfoMail(UserWPB.java:507)
        at at.balecon.portal.ui.UserWPB.onSave(UserWPB.java:392)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.eclnt.jsfserver.util.StackedMethodExpression.invoke(StackedMethodExpression.java:109)
        ... 91 more

**Comment by meeximum** [comment]
so I call in Coding

```
Mailer mailer = MailerBuilder.withSMTPServerHost(ConfigService.getInstance().getMailHost())
				.withSMTPServerPort(ConfigService.getInstance().getMailPort())
				.withSMTPServerUsername(ConfigService.getInstance().getMailUsername())
				.withSMTPServerPassword(ConfigService.getInstance().getMailPassword())
				.withTransportStrategy(TransportStrategy.SMTP_TLS).buildMailer();

EmailPopulatingBuilder emailPB = EmailBuilder.startingBlank();

Email email = emailPB.buildEmail();

mailer.sendMail(email, false);
```

**Comment by bbottema** [comment]
This is very strange, somehow Jacoco instrumented code ended up in Maven central for [clustered-object-pool](https://github.com/bbottema/clustered-object-pool), which is explicitly excluded in the pipeline config. I'll have to check and re-release it.

**Comment by bbottema** [comment]
This is a known issue, please update to 8.8.2 (I think, or else 8.8.3).
