### ISSUE TITLE
jakarta.activation.MailcapCommandMap tries to load javax.activation.DataContentHandler

### ISSUE THREAD

**Issue by eischet** [bbottema/simple-java-mail#559]
I'm getting an exception parsing some mails that looks like Jakarta Activation is trying to load javax.activation classes...?
This happens *very* infrequently, i.e. one mail in thousands triggers this.

I don't have access to the original mail for this exception, I'm afraid. Because it contains sensitive information that my customer may not let me see. The mail comes from the MS Graph API, in case that matters, as an InputStream.

```
    InputStream content = graphClient.users().byUserId(settings.getUsername()).messages().byMessageId(id).content().get();      
    MimeMessage mimeMessage = EmailConverter.emlToMimeMessage(content, session);
    Email m = EmailConverter.mimeMessageToEmailBuilder(mimeMessage, null).buildEmail();
```

Stack trace:

```
Caused by: java.lang.NoClassDefFoundError: javax/activation/DataContentHandler
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at jakarta.activation.MailcapCommandMap.getDataContentHandler(MailcapCommandMap.java:594)
        at jakarta.activation.MailcapCommandMap.createDataContentHandler(MailcapCommandMap.java:554)
        at jakarta.activation.CommandMap.createDataContentHandler(CommandMap.java:205)
        at jakarta.activation.DataHandler.getDataContentHandler(DataHandler.java:587)
        at jakarta.activation.DataHandler.getContent(DataHandler.java:514)
        at jakarta.mail.internet.MimeMessage.getContent(MimeMessage.java:1504)
        at org.simplejavamail.converter.internal.mimemessage.MimeMessageParser.parseContent(MimeMessageParser.java:268)
        at org.simplejavamail.converter.internal.mimemessage.MimeMessageParser.parseMimePartTree(MimeMessageParser.java:112)
        at org.simplejavamail.converter.internal.mimemessage.MimeMessageParser.parseMimeMessage(MimeMessageParser.java:89)
        at org.simplejavamail.converter.EmailConverter.mimeMessageToEmailBuilder(EmailConverter.java:138)
        at org.simplejavamail.converter.EmailConverter.mimeMessageToEmailBuilder(EmailConverter.java:125)

```

Any ideas what might trigger this? 

My jars should be correct, I hope, even though there's the old servlet and annotation API in between:

```
ls jakarta* javax* simple-java* *angus* *jmail*
angus-activation-2.0.2.jar
angus-mail-2.0.3.jar
jakarta.activation-2.0.1.jar
jakarta.activation-api-2.1.3.jar
jakarta.annotation-api-3.0.0.jar
jakarta.mail-api-2.1.3.jar
jakarta.xml.bind-api-3.0.1.jar
javax.annotation-api-1.3.1.jar
javax.servlet-api-3.1.0.jar
jmail-1.6.3.jar
simple-java-mail-8.12.2.jar
```

Regards,
Stefan

**Comment by bbottema** [comment]
Hi, sorry for the late reply! I've been extremely busy.

If you haven't completely moved on yet, I'd advise you to run `mvn dependency:tree` and see where the javax dependency is coming from. Other than that it could be a parent-first application server class loading issue. Good luck.

**Comment by eischet** [comment]
Hi Benny, no problem and thanks for the reply. 

There's no app server here, but embedded Jetty 12, so there should be no parent classloading here at all. And I'm on Gradle at the moment, but migrating back to Maven ASAP.

I think your suggestion is backwards, though: The javax.activation dependency is **missing** in my app, as suggested, which is what **causes** the error message, because for reasons beyond my understanding, the jakarta.activation still tries to load code from javax.activation. Adding the outdated javax.activation JAR might even **fix** this error, but I'm afraid that could introduce more weird bugs instead.

**Comment by bbottema** [comment]
Ahh, I see! Yes, Simple Java Mail no longer has any references to `javax.activation`, so this issue doesn’t tie back to the library. However, since the early days of Sun JavaMail (20 some years ago), the framework has included a mechanism in the `MailcapCommandMap` to load classes at runtime to support MIME types. It seems a javax data handlers creeps in from somewhere.

It seems something in your setup is causing `MailcapCommandMap` to look for a handler in the old `javax.activation` namespace, which is unrelated to the modern `jakarta.activation`. This is likely due to a dependency on your classpath referencing `javax.activation` instead of the newer Jakarta API.

As suggested earlier, I recommend reviewing your classpath to ensure all libraries are the Jakarta versions. `mvn dependency:tree` or `gradle dependencies` should help.

**Comment by bbottema** [comment]
Ahh, I see!

Yes, Simple Java Mail no longer has any references to `javax.activation`, so this issue doesn’t tie back to the library. However, since the early days of Sun JavaMail (20 some years ago), the underlying mailing framework has included a mechanism in the `MailcapCommandMap` to load classes at runtime to support MIME types.

It seems that this issue is caused by a `MailcapCommandMap` entry that defines a `javax.activation` class name as a MIME type handler, which then fails at runtime because the `javax.activation` package is missing from your classpath. These handlers are configured by name, not directly loaded as part of your dependencies, and may originate from default MIME type mappings or custom configurations.

For example, similar to how I add new MIME type handlers like this in my own code:  

```java
static {
    MailcapCommandMap mc = (MailcapCommandMap) CommandMap.getDefaultCommandMap();
    mc.addMailcap("text/calendar;; x-java-content-handler=" + text_calendar.class.getName());
    CommandMap.setDefaultCommandMap(mc);
}
```
Something in your setup might be introducing an outdated handler pointing to `javax.activation.DataContentHandler`.  

To resolve this, review the default or custom `MailcapCommandMap` configurations in your application or dependencies to identify any lingering references to `javax.activation`. Replacing them with their Jakarta equivalents or overriding them with modern handlers should resolve the issue.

**Comment by eischet** [comment]
Thank you so much, you just solved this issue for me. :-) 

Looking at https://docs.oracle.com/javase/8/docs/api/javax/activation/MailcapCommandMap.html I now understand where MailcapCommandMap gets plugins from, and there is in fact an unwanted and outdated "mailcap" file in at least one of my dependencies (bcmail). Repackaging, upgrading or removing the "rogue" jars should solve this issue.

Makes you wonder why the jakarta guys kept the same file name ("mailcap") from the javax code instead of using the modern service loader approach, which disambiguates those files by naming them like the interface of the service, META-INF/services/org.slf4j.spi.SLF4JServiceProvider. I think that was a bad decision on their part because legacy mailcap entries will **always** collide with the new jakarta libs, introducing a totally unnecessary source of errors.
 
Your MailcapCommandMap, however, is already "disambiguated" implicitly because you imported it from the jakarta package. So, fortunately, looking for mailcap files should be sufficient, and I won't have to go hunting through any binary code.

Case closed! And thanks, your help, and your work on this great lib, is really appreciated.
