### ISSUE TITLE
Mail sending not working since v8.6.0

### ISSUE THREAD

**Issue by kurtjmeyoung** [bbottema/simple-java-mail#564]
Hello,

since v8.6.0 I get the following stacktrace when attempting to send out a mail (up to current v8.12.2). v8.5.1 is working without any issues for me. Maybe I need to configure something differently since v8.6.0 and I'm just overseeing the information somewhere?  Would really appreciate If you could help me figure it out.

I'm using jdk 21.0.5

simplified code:

```
MailerBuilder mailer = MailerBuilder
                .withSMTPServer("<host.ip.address>", 25)
                .async()
                .buildMailer();

EmailPopulatingBuilder emailBuilder = EmailBuilder.startingBlank()
                .to("<recipient.mail.address>")
                .from("<from.mail.address>")
                .withSubject("<subject>")
                .withHTMLText("<html body>");

mailer.sendMail(emailBuilder.buildEmail());
```

Stacktrace:

```
[ERROR] [o.s.i.u.c.NamedRunnable] - Failed to run sendMail process
org.simplejavamail.mailer.internal.MailerException: Failed to send email [Subject: '<subject>'], reason: Third party error
	at org.simplejavamail.mailer.internal.SendMailClosure.handleException(SendMailClosure.java:85)
	at org.simplejavamail.mailer.internal.SendMailClosure.executeClosure(SendMailClosure.java:72)
	at org.simplejavamail.mailer.internal.AbstractProxyServerSyncingClosure.run(AbstractProxyServerSyncingClosure.java:56)
	at org.simplejavamail.internal.util.concurrent.NamedRunnable.run(NamedRunnable.java:40)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
Caused by: jakarta.mail.MessagingException: Could not convert socket to TLS
	at org.eclipse.angus.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:2173)
	at org.eclipse.angus.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:741)
	at jakarta.mail.Service.connect(Service.java:345)
	at jakarta.mail.Service.connect(Service.java:225)
	at jakarta.mail.Service.connect(Service.java:174)
Caused by: java.io.IOException: Can't verify identity of server: <host.ip.address>
	at org.eclipse.angus.mail.util.SocketFetcher.checkServerIdentity(SocketFetcher.java:699)
	at org.eclipse.angus.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:636)
	at org.eclipse.angus.mail.util.SocketFetcher.startTLS(SocketFetcher.java:555)
	at org.eclipse.angus.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:2168)
	at org.eclipse.angus.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:741)
```

**Comment by bbottema** [comment]
Yes, this is a known issue mentioned in the release notes for 8.6.0, caused by _Angus_ (the successor to the Jakarta mail implementation); they changed a critical default for checking server identity.

It's detailed in the front page when you visit the project in GitHub under the 8.6.0 release notes. Good luck!
